# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 413)
        self.messageContentTextBox = QtWidgets.QPlainTextEdit(Dialog)
        self.messageContentTextBox.setGeometry(QtCore.QRect(40, 120, 551, 111))
        self.messageContentTextBox.setObjectName("messageContentTextBox")
        self.filenameTextBox = QtWidgets.QPlainTextEdit(Dialog)
        self.filenameTextBox.setGeometry(QtCore.QRect(40, 60, 191, 31))
        self.filenameTextBox.setObjectName("filenameTextBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 40, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 250, 171, 16))
        self.label_3.setObjectName("label_3")
        self.pathTextBox = QtWidgets.QPlainTextEdit(Dialog)
        self.pathTextBox.setGeometry(QtCore.QRect(40, 270, 551, 31))
        self.pathTextBox.setObjectName("pathTextBox")
        self.saveMessageButton = QtWidgets.QPushButton(Dialog)
        self.saveMessageButton.setGeometry(QtCore.QRect(150, 350, 151, 41))
        self.saveMessageButton.setObjectName("saveMessageButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(310, 350, 141, 41))
        self.cancelButton.setObjectName("cancelButton")
        self.msg = QtWidgets.QLabel(Dialog)
        self.msg.setGeometry(QtCore.QRect(40, 310, 201, 21))
        self.msg.setText("")
        self.msg.setObjectName("msg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Filename"))
        self.label_2.setText(_translate("Dialog", "Message content"))
        self.label_3.setText(_translate("Dialog", "Path where file will be saved"))
        self.saveMessageButton.setText(_translate("Dialog", "Save message to file"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
