# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/PassphraseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PassphraseDialog(object):
    def setupUi(self, PassphraseDialog):
        PassphraseDialog.setObjectName("PassphraseDialog")
        PassphraseDialog.setEnabled(True)
        PassphraseDialog.resize(400, 191)
        PassphraseDialog.setWindowOpacity(1.0)
        PassphraseDialog.setToolTipDuration(-2)
        PassphraseDialog.setAccessibleName("")
        self.OKBox = QtWidgets.QDialogButtonBox(PassphraseDialog)
        self.OKBox.setGeometry(QtCore.QRect(30, 110, 341, 32))
        self.OKBox.setOrientation(QtCore.Qt.Horizontal)
        self.OKBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.OKBox.setObjectName("OKBox")
        self.PassphraseText = QtWidgets.QTextEdit(PassphraseDialog)
        self.PassphraseText.setGeometry(QtCore.QRect(30, 50, 341, 41))
        self.PassphraseText.setObjectName("PassphraseText")
        self.label = QtWidgets.QLabel(PassphraseDialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.label.setObjectName("label")
        self.passphraseLabel = QtWidgets.QLabel(PassphraseDialog)
        self.passphraseLabel.setGeometry(QtCore.QRect(40, 160, 55, 16))
        self.passphraseLabel.setText("")
        self.passphraseLabel.setObjectName("passphraseLabel")

        self.retranslateUi(PassphraseDialog)
        self.OKBox.accepted.connect(PassphraseDialog.accept) # type: ignore
        self.OKBox.rejected.connect(PassphraseDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PassphraseDialog)

    def retranslateUi(self, PassphraseDialog):
        _translate = QtCore.QCoreApplication.translate
        PassphraseDialog.setWindowTitle(_translate("PassphraseDialog", "Enter passphrase"))
        self.label.setText(_translate("PassphraseDialog", "Passphrase:"))
