# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ShowPrivateKeyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(603, 400)
        self.showPrivateKeyDialogPassphrase = QtWidgets.QPlainTextEdit(Dialog)
        self.showPrivateKeyDialogPassphrase.setGeometry(QtCore.QRect(190, 50, 201, 31))
        self.showPrivateKeyDialogPassphrase.setObjectName("showPrivateKeyDialogPassphrase")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 30, 81, 16))
        self.label.setObjectName("label")
        self.showPrivateKeyDialogOK = QtWidgets.QPushButton(Dialog)
        self.showPrivateKeyDialogOK.setGeometry(QtCore.QRect(190, 100, 93, 28))
        self.showPrivateKeyDialogOK.setObjectName("showPrivateKeyDialogOK")
        self.showPrivateKeyDialogCancel = QtWidgets.QPushButton(Dialog)
        self.showPrivateKeyDialogCancel.setGeometry(QtCore.QRect(300, 100, 93, 28))
        self.showPrivateKeyDialogCancel.setObjectName("showPrivateKeyDialogCancel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 190, 221, 16))
        self.label_2.setObjectName("label_2")
        self.showPrivateKeyDialogPrivateKey = QtWidgets.QPlainTextEdit(Dialog)
        self.showPrivateKeyDialogPrivateKey.setGeometry(QtCore.QRect(80, 210, 441, 161))
        self.showPrivateKeyDialogPrivateKey.setObjectName("showPrivateKeyDialogPrivateKey")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Show private key"))
        self.label.setText(_translate("Dialog", "Passphrase:"))
        self.showPrivateKeyDialogOK.setText(_translate("Dialog", "OK"))
        self.showPrivateKeyDialogCancel.setText(_translate("Dialog", "Close"))
        self.label_2.setText(_translate("Dialog", "Decrypted private key"))
